#ServerPort
server:
  port: 8001

#ConfigImport
spring:
  application:
    name: nebula
  profiles:
    active: jwt, datasource
  config:
    import:
      - optional:configserver:http://3.36.67.38:8001
#JpaConfig
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#Multipart
  servlet:
    multipart:
      location: classpath:tempfile

