#ServerPort
server:
  port: 8001

#ConfigImport
spring:
  application:
    name: nebula
  profiles:
    active: jwt, datasource, aws, gmail
  config:
    import:
      - optional:configserver:http://ip-172-31-1-205.ap-northeast-2.compute.internal:8001
#JpaConfig
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: official.52hertz@gmail.com
    password: sefyoqhecokygyzb
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
#Multipart
  servlet:
    multipart:
      location: classpath:tempfile
#Hikari Refresh
  cloud:
    refresh:
      extra-refreshable: javax.sql.DataSource

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh

