#ServerPort
server:
  port: 8001

#ConfigImport
spring:
  application:
    name: nebula
  config:
    import:
      - optional:configserver:http://3.36.99.142:8001
#JpaConfig
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#Multipart
  servlet:
    multipart:
      location: classpath:tempfile

