#ServerPort
server:
  port: 8001

#ConfigImport
spring:
  application:
    name: nebula
  profiles:
    active: jwt, datasource
  config:
    import:
      - optional:configserver:http://43.201.47.26:8001
#JpaConfig
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#Multipart
  servlet:
    multipart:
      location: classpath:tempfile
#Hikari Refresh
  cloud:
    refresh:
      extra-refreshable: javax.sql.DataSource

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh
